---
jobs:
- name: build
  plan:
  - aggregate:
    - get: concourse-packer
    - get: concourse-release
      trigger: true
      params:
        globs:
          - concourse_linux_amd64
  - task: prepare-release
    file: concourse-packer/tasks/prepare-release.yml
    params:
      CONFIG: |
        "aws_access_key": {{aws-access-key-id}}, "aws_secret_key": {{aws-secret-access-key}}, "aws_region": {{aws-default-region}}
  - put: packer-aws
    params:
      template: prepare-release/bootstrap_concourse.json
      var_file: prepare-release/secrets.json
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to build Concourse AMI
          <https://ci.anvil.pcfdemo.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully built Concourse AMI
          <https://ci.anvil.pcfdemo.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}

resources:
- name: concourse-packer
  type: git
  source:
    uri: {{concourse-packer-git-url}}
    branch: {{concourse-packer-git-branch}}

- name: concourse-release
  type: github-release
  source:
    user: concourse
    repository: concourse
    access_token: {{concourse-packer-git-access-token}}

- name: packer-aws
  type: packer
  source:
    aws_access_key_id: {{aws-access-key-id}}
    aws_secret_access_key: {{aws-secret-access-key}}
    region: {{aws-default-region}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: packer
  type: docker-image
  source:
    repository: jdub/packer-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
