---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 14.04

inputs:
  - name: concourse-packer
  - name: concourse-release

outputs:
  - name: prepare-release

params:
  CONFIG:

run:
  path: concourse-packer/tasks/prepare-release.sh
